name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "/home/runner/work/api-manager/"
          REMOTE_HOST: '34.64.236.239'
          REMOTE_USER: 'github'
          TARGET: '/home/github/api-manager2'
          EXCLUDE: "/.git/, /*.pem/"
          SCRIPT_BEFORE: |
            whoami
            ls -al
          SCRIPT_AFTER: |
            whoami
            ls -al ./api-manager2
            echo $RSYNC_STDOUT
