name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Deploy with rsync
        run: |
          rsync -avz --delete -e "ssh -i ${{ secrets.SSH_PRIVATE_KEY }}" ./path/to/local/dir/ github@34.64.236.239:/home/github/api-manager
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
