name: Deploy to tmp.useb.co.kr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rsync
        run: sudo apt-get install rsync

      - name: Deploy code to server
        run: |
          echo ${{ secrets.SSH_KEY }}
          rsync -avz --delete -e "ssh -i ${{ secrets.SSH_KEY }}" --exclude '.git*' ./ github@34.64.236.239:/home/github

        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
