name: Deploy to tmp.useb.co.kr

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SSH client
        run: sudo apt-get install openssh-client
      
      - name: Deploy code to internal IP server
        run: scp -r -P 22 ./chae@${{ variables.SSH_HOST }}:/home/chae/api-manager
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
